name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  
  Build_All:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build all
        run: nix build 
  Flake_Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use local my-action
        uses: ./.github/actions/setup
        with:
          cachix_auth_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run flake check
          run: nix flake check --all-systems
  CI-CD:
    timeout-minutes: 360
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf:
            accept-flake-config = true

      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: nix flake check
        run: nix flake check